replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

auth:
  username: admin
  password: admin
  database: tododb

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: standard